services:
  stats-server:
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: practicum
      POSTGRES_PASSWORD: practicum
    ports:
      - "5432:5432"
    volumes:
      - stats-db-data:/var/lib/postgresql/data
  volumes:
    stats-db-data:

  main-service:
    image: main-service

  main-db:
    image: postgres:16.1

  gateway-server:
    ports:
      - "8080:8080"